"""job runs

Revision ID: 08d5fe5a4657
Revises: 7cbb79a86b3e
Create Date: 2026-09-25 10:48:36.459997

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "08d5fe5a4657"
down_revision: str | Sequence[str] | None = "7cbb79a86b3e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("agent_run", schema=None) as batch_op:
        batch_op.add_column(sa.Column("instructions", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("workspace", sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column("log", sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f("ix_agent_run_task_id"), ["task_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("agent_run", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_run_task_id"))
        batch_op.drop_column("log")
        batch_op.drop_column("workspace")
        batch_op.drop_column("instructions")

    # ### end Alembic commands ###
