"""debates

Revision ID: 168c4d2e699c
Revises: bf32cbb696fe
Create Date: 2026-09-25 19:33:38.488392

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "168c4d2e699c"
down_revision: str | Sequence[str] | None = "bf32cbb696fe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "debate",
        sa.Column("channel_id", sa.String(length=36), nullable=False),
        sa.Column("topic", sa.Text(), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("participants_json", sa.JSON(), nullable=False),
        sa.Column("moderator", sa.String(length=40), nullable=False),
        sa.Column("max_rounds", sa.Integer(), nullable=False),
        sa.Column("rounds_done", sa.Integer(), nullable=False),
        sa.Column("use_tools", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("thread_root_id", sa.String(length=36), nullable=True),
        sa.Column("summary_message_id", sa.String(length=36), nullable=True),
        sa.Column("summary_task_id", sa.String(length=36), nullable=True),
        sa.Column("summary_note_id", sa.String(length=36), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["channel_id"], ["channel.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("debate")
    # ### end Alembic commands ###
