"""routines

Revision ID: 1876c629a9bb
Revises: e89719f706e0
Create Date: 2026-09-24 23:36:26.950071

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1876c629a9bb"
down_revision: str | Sequence[str] | None = "e89719f706e0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "routine",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("weekdays", sa.String(length=7), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "routine_check",
        sa.Column("routine_id", sa.String(length=36), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["routine_id"], ["routine.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("routine_id", "day", name="uq_routine_check_day"),
    )
    with op.batch_alter_table("routine_check", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_routine_check_routine_id"), ["routine_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("routine_check", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_routine_check_routine_id"))

    op.drop_table("routine_check")
    op.drop_table("routine")
    # ### end Alembic commands ###
