"""coding mode

Revision ID: 29e2c75b6680
Revises: 167f210db68c
Create Date: 2026-09-28 20:58:20.154521

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "29e2c75b6680"
down_revision: str | Sequence[str] | None = "167f210db68c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("channel", schema=None) as batch_op:
        batch_op.add_column(sa.Column("workspace_path", sa.String(length=500), nullable=True))

    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.add_column(sa.Column("coding", sa.Boolean(), server_default="0", nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Plain DROP COLUMN: recreating these tables (batch mode) fails on foreign keys.
    op.execute("ALTER TABLE message DROP COLUMN coding")
    op.execute("ALTER TABLE channel DROP COLUMN workspace_path")
