"""approvals

Revision ID: 36b2026b0e93
Revises: 1876c629a9bb
Create Date: 2026-09-25 01:32:18.862128

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "36b2026b0e93"
down_revision: str | Sequence[str] | None = "1876c629a9bb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "approval",
        sa.Column("requested_by", sa.String(length=100), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=True),
        sa.Column("channel_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("summary", sa.String(length=500), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["channel_id"], ["channel.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("approval", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_approval_channel_id"), ["channel_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_approval_status"), ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("approval", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_approval_status"))
        batch_op.drop_index(batch_op.f("ix_approval_channel_id"))

    op.drop_table("approval")
    # ### end Alembic commands ###
