"""core domain tables

Revision ID: 49ec2ed6f196
Revises: cda5b1882f0a
Create Date: 2026-09-24 21:30:08.884031

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "49ec2ed6f196"
down_revision: str | Sequence[str] | None = "cda5b1882f0a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_log",
        sa.Column("object_type", sa.String(length=50), nullable=False),
        sa.Column("object_id", sa.String(length=36), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("before_json", sa.JSON(), nullable=True),
        sa.Column("after_json", sa.JSON(), nullable=True),
        sa.Column("actor", sa.String(length=100), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("activity_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_activity_log_object_id"), ["object_id"], unique=False)

    op.create_table(
        "area",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("icon", sa.String(length=20), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "inbox_item",
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("captured_via", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("suggestion_json", sa.JSON(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("inbox_item", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_inbox_item_status"), ["status"], unique=False)

    op.create_table(
        "channel",
        sa.Column("area_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("default_agent_id", sa.String(length=36), nullable=True),
        sa.Column("vault_path", sa.String(length=500), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["area_id"], ["area.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "event",
        sa.Column("channel_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("starts_at", sa.DateTime(), nullable=True),
        sa.Column("ends_at", sa.DateTime(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("location", sa.String(length=500), nullable=True),
        sa.Column("rrule", sa.String(length=500), nullable=True),
        sa.Column("calendar_id", sa.String(length=200), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["channel_id"], ["channel.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_event_channel_id"), ["channel_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_event_start_date"), ["start_date"], unique=False)
        batch_op.create_index(batch_op.f("ix_event_starts_at"), ["starts_at"], unique=False)

    op.create_table(
        "message",
        sa.Column("channel_id", sa.String(length=36), nullable=False),
        sa.Column("thread_root_id", sa.String(length=36), nullable=True),
        sa.Column("author_type", sa.String(length=20), nullable=False),
        sa.Column("author_id", sa.String(length=36), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("ref_type", sa.String(length=50), nullable=True),
        sa.Column("ref_id", sa.String(length=36), nullable=True),
        sa.Column("run_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["channel_id"], ["channel.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["thread_root_id"],
            ["message.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_message_channel_id"), ["channel_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_message_thread_root_id"), ["thread_root_id"], unique=False
        )

    op.create_table(
        "task",
        sa.Column("channel_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("position", sa.Float(), nullable=False),
        sa.Column("due_at", sa.DateTime(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["channel_id"], ["channel.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_task_channel_id"), ["channel_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_task_due_at"), ["due_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_task_due_at"))
        batch_op.drop_index(batch_op.f("ix_task_channel_id"))

    op.drop_table("task")
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_message_thread_root_id"))
        batch_op.drop_index(batch_op.f("ix_message_channel_id"))

    op.drop_table("message")
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_event_starts_at"))
        batch_op.drop_index(batch_op.f("ix_event_start_date"))
        batch_op.drop_index(batch_op.f("ix_event_channel_id"))

    op.drop_table("event")
    op.drop_table("channel")
    with op.batch_alter_table("inbox_item", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_inbox_item_status"))

    op.drop_table("inbox_item")
    op.drop_table("area")
    with op.batch_alter_table("activity_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_activity_log_object_id"))

    op.drop_table("activity_log")
    # ### end Alembic commands ###
