"""message pin and inbox channel

Revision ID: 55afcd5757bd
Revises: 49ec2ed6f196
Create Date: 2026-09-24 22:48:45.959916

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "55afcd5757bd"
down_revision: str | Sequence[str] | None = "49ec2ed6f196"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("inbox_item", schema=None) as batch_op:
        batch_op.add_column(sa.Column("channel_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_inbox_item_channel_id"), ["channel_id"], unique=False)
        batch_op.create_foreign_key(
            "fk_inbox_item_channel_id_channel",
            "channel",
            ["channel_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.add_column(sa.Column("pinned", sa.Boolean(), server_default="0", nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.drop_column("pinned")

    with op.batch_alter_table("inbox_item", schema=None) as batch_op:
        batch_op.drop_constraint("fk_inbox_item_channel_id_channel", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_inbox_item_channel_id"))
        batch_op.drop_column("channel_id")

    # ### end Alembic commands ###
