"""source links

Revision ID: 6bb5fb945a69
Revises: 08d5fe5a4657
Create Date: 2026-09-25 15:32:46.729303

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6bb5fb945a69"
down_revision: str | Sequence[str] | None = "08d5fe5a4657"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_link",
        sa.Column("object_type", sa.String(length=20), nullable=False),
        sa.Column("object_id", sa.String(length=36), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("external_id", sa.String(length=1000), nullable=False),
        sa.Column("calendar_url", sa.String(length=1000), nullable=False),
        sa.Column("calendar_name", sa.String(length=200), nullable=False),
        sa.Column("uid", sa.String(length=500), nullable=False),
        sa.Column("etag", sa.String(length=200), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("read_only", sa.Boolean(), nullable=False),
        sa.Column("local_updated_at", sa.DateTime(), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(), nullable=True),
        sa.Column("conflict", sa.JSON(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "external_id", name="uq_source_link_external"),
    )
    with op.batch_alter_table("source_link", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_source_link_object_id"), ["object_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("source_link", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_source_link_object_id"))

    op.drop_table("source_link")
    # ### end Alembic commands ###
