"""agents and runs

Revision ID: 7e29dc905965
Revises: 36b2026b0e93
Create Date: 2026-09-25 03:30:35.704204

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e29dc905965"
down_revision: str | Sequence[str] | None = "36b2026b0e93"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent",
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("avatar", sa.String(length=10), nullable=True),
        sa.Column("backend", sa.String(length=20), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=True),
        sa.Column("system_prompt", sa.Text(), nullable=True),
        sa.Column("tools_json", sa.JSON(), nullable=True),
        sa.Column("is_builtin", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "agent_run",
        sa.Column("agent_id", sa.String(length=36), nullable=False),
        sa.Column("channel_id", sa.String(length=36), nullable=False),
        sa.Column("thread_root_id", sa.String(length=36), nullable=True),
        sa.Column("trigger_message_id", sa.String(length=36), nullable=True),
        sa.Column("reply_message_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("task_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agent.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["channel_id"], ["channel.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agent_run", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_agent_run_agent_id"), ["agent_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_agent_run_thread_root_id"), ["thread_root_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_agent_run_trigger_message_id"), ["trigger_message_id"], unique=False
        )

    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sticky_agent_id", sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.drop_column("sticky_agent_id")

    with op.batch_alter_table("agent_run", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_run_trigger_message_id"))
        batch_op.drop_index(batch_op.f("ix_agent_run_thread_root_id"))
        batch_op.drop_index(batch_op.f("ix_agent_run_agent_id"))

    op.drop_table("agent_run")
    op.drop_table("agent")
    # ### end Alembic commands ###
