export const enTemplates: Record<string, string> = {
  "#{0} 삭제": "Delete #{0}",
  "{0} 종일": "{0} · all day",
  "{0} 다시 열기": "Reopen {0}",
  "{0} 완료 처리": "Mark {0} complete",
  "완료했어요 · {0}": "Completed · {0}",
  "완료 · {0}초": "Done · {0}s",
  "{0} 응답 중단": "Stop {0}'s response",
  "{0}에게 메시지": "Message {0}",
  "{0}에 적기 — 그냥 쓰면 Argos가 알아서 정리해요":
    "Write in {0} — Argos will organize it for you",
  " · {0}분": " · {0} min",
  "잡 완료{0}": "Job completed{0}",
  "잡 실패{0}": "Job failed{0}",
  "{0} · 우클릭하여 삭제": "{0} · right-click to delete",
  "{0} 영역 삭제": "Delete {0} space",
  "{0} 추가": "Add {0}",
  "{0} 채널 추가": "Add {0} channel",
  "{0}분 전": "{0} min ago",
  "{0}시간 전": "{0} hr ago",
  " · {0} 뒤 초기화 ({1})": " · Resets in {0} ({1})",
  "{0} 동기화 오류": "{0} sync failed",
  "테마: {0} (눌러서 바꾸기)": "Theme: {0} (click to change)",
  '"{0}"을(를) 삭제할까요?': 'Delete "{0}"?',
  "{0} 수정": "Edited {0}",
  " · 답글 {0}": " · {0} replies",
  "마감 · {0}": "Due · {0}",
  "'{0}' 캘린더의 일정이라 캘린더 앱에서 고쳐 주세요.":
    "This event belongs to the '{0}' calendar. Edit it in Calendar.",
  '"{0}" 일정을 삭제할까요?': 'Delete the event "{0}"?',
  " · /ask 채널 {0}개": " · /ask in {0} channels",
  "@{0} 에이전트를 지울까요? 1:1 대화도 함께 지워져요.":
    "Delete agent @{0}? Its direct message history will also be deleted.",
  "@{0} 수정": "Edit @{0}",
  "{0}개 모델": "{0} models",
  "*(첨부: {0})*": "*(Attachment: {0})*",
  "순서 바꾸기 (지금: {0})": "Change sort order (currently: {0})",
  " · 메신저 실패: {0}": " · Messenger failed: {0}",
  "마지막 {0} · {1}개 보관 중": "Last backup {0} · {1} retained",
  "{0} 설치됨 · 다시 시작하면 적용돼요":
    "Version {0} installed · Restart to apply",
  "{0} 받는 중…": "Downloading {0}…",
  "최신 버전이에요 · {0} 확인": "Up to date · Checked {0}",
  "{0} 모델": "{0} model",
  "{0} 삭제": "Delete {0}",
  " {0}분마다 자동으로 맞춰요.": " Syncs automatically every {0} min.",
  "마지막 동기화 {0}{1}": "Last synced {0}{1}",
  "{0} 일정을 넣을 채널": "Channel for {0} events",
  "{0} (볼트 설정에서 찾음)": "{0} (found in vault settings)",
  "노트 {0}개 · {1}{2}": "{0} notes · {1}{2}",
  "{0}분 뒤": "In {0} min",
  "{0}시간 {1}분 뒤": "In {0} hr {1} min",
  "{0}일 이내": "Within {0} days",
  "정리 안 된 입력 {0}": "{0} unprocessed items",
  "{0}에서 Argos {1} 지울까요?": "Remove Argos {1} from {0}?",
  "{0} 편집": "Edit {0}",
  '"{0}" 루틴과 체크 기록을 삭제할까요?':
    'Delete routine "{0}" and its check history?',
};
