export const en: Record<string, string> = {
  "이 채널과 메시지를 삭제할까요? 연결된 옵시디언 노트 파일은 남아요.":
    "Delete this channel and its messages? Linked Obsidian notes will remain.",
  "이 채널에는 할 일이나 일정도 있어요. 계속하면 함께 삭제됩니다.":
    "This channel also has tasks and events. They'll be deleted together if you continue.",
  취소: "Cancel",
  "모두 삭제": "Delete all",
  "채널 삭제": "Delete channel",
  "로컬 모델": "Local model",
  에이전트: "Agent",
  백로그: "Backlog",
  "할 일": "Task",
  "진행 중": "In progress",
  검토: "Review",
  완료: "Done",
  일정: "Event",
  아이디어: "Idea",
  "공부 노트": "Study note",
  "내 공간": "My space",
  "넘긴 입력이에요.": "Skipped item.",
  "분류하지 못했어요 · 원문은 인박스에 보관됨":
    "Couldn't classify this · Original saved to Inbox",
  "다시 시도": "Try again",
  "알아보는 중": "Classifying",
  "인박스에 보관됨 · 분류 모델이 설정되지 않았어요":
    "Saved to Inbox · Categorization model not set",
  정리됨: "Organized",
  "인박스에 두었어요": "Saved to Inbox",
  알아봤어요: "Suggested classification",
  "(으)로 정리할까요?": "?",
  확신도: "Confidence",
  유형: "Type",
  제목: "Title",
  채널: "Channel",
  "새 대화": "New chat",
  코딩: "Coding",
  "코딩 모드 — 작업 폴더에서 파일·셸을 다뤄요 (/로 스킬)":
    "Coding mode — files and shell in the project folder (/ for skills)",
  "작업 폴더 (코딩 모드, 선택)": "Project folder (coding mode, optional)",
  "예: my-project (코딩 잡 허용 폴더 안)":
    "e.g. my-project (inside the allowed job folders)",
  "정하면 입력창의 코딩 토글로 Claude·Codex가 이 폴더에서 파일·셸·네트워크를 써요.":
    "With a folder set, the Coding toggle lets Claude and Codex use files, shell and network in it.",
  "대화 고르기": "Choose conversation",
  "(현재)": "(current)",
  "새 대화예요. 이전 대화는 위에서 고를 수 있어요.":
    "A new conversation. Pick earlier ones above.",
  "· 채널 맥락으로 확정": "· Matched to this channel",
  "정해지지 않음 · 고치기에서 골라 주세요":
    "Not set · Choose a channel in Edit",
  "노트로 저장": "Save as Note",
  추가하기: "Add",
  고치기: "Edit",
  "인박스에 두기": "Keep in Inbox",
  "원문은 인박스에 보관됨": "Original is kept in Inbox",
  일시: "Date & Time",
  "M월 d일 (EEE) HH:mm": "M/d (EEE) HH:mm",
  "M월 d일 (EEE)": "M/d (EEE)",
  마감: "Due",
  "아이디어 (백로그)": "Idea (Backlog)",
  "골라 주세요": "Please choose",
  시작: "Start",
  끝: "End",
  "또는 종일": "or All day",
  "마감 (선택)": "Due (Optional)",
  "M월 · EEE": "MMM · EEE",
  종일: "All day",
  "분류하지 못했어요": "Uncategorized",
  "채널 미정": "No channel selected",
  "채널 고르기": "Select channel",
  "채널 골라 저장": "Save to Channel",
  "채널 골라 추가": "Add to Channel",
  "승인하고 삭제": "Approve & Delete",
  "승인 필요": "Needs approval",
  요청: "Request",
  승인: "Approve",
  거절: "Reject",
  승인됨: "Approved",
  거절됨: "Rejected",
  "실행 실패": "Execution failed",
  돌아가며: "Alternating",
  찬반: "For/Against",
  "사회자 진행": "Moderated",
  끝남: "Ended",
  중단됨: "Stopped",
  "오류로 멈춤": "Stopped by Error",
  결론: "Conclusion",
  개선안: "Revised proposal",
  토론: "Discussion",
  "라운드 ·": "Round ·",
  "· 사회": "· Facilitator",
  " · 도구 사용": " · Tools enabled",
  "발언이 스레드에 이어지고 있어요. 스레드에 쓰면 다음 차례부터 반영돼요.":
    "Your message continues the thread. Posting to a thread will reflect in future turns.",
  "개선안 (최종본)": "Revised proposal (final)",
  "스레드 보기": "View thread",
  중단: "Stop",
  "할 일로 만듦": "Made into task",
  "할 일로": "To task",
  "노트로 저장함": "Saved as note",
  노트로: "To note",
  되돌리기: "Undo",
  "제목 [날짜] [시간] — 할 일": "Title [Date] [Time] — Task",
  "제목 날짜 [시작-끝] — 일정": "Title Date [Start-End] — Event",
  "내용 — 공부 노트": "Content — Study note",
  "질문 — 기본 에이전트에게": "Question — to default agent",
  "@claude|@codex 할 일 [--dir 경로] — 코딩 잡":
    "@claude|@codex task [--dir path] — Coding job",
  "@a @b 주제 [--mode] [--rounds N] — 토론":
    "@a @b topic [--mode] [--rounds N] — Discussion",
  메시지: "Message",
  "이전 메시지 더 보기": "View previous messages",
  "에 첫 메시지를 적어 보세요. 그냥 쓰면 Argos가 할 일·일정으로 정리해요.":
    "Write your first message here. Just typing will let Argos organize it into tasks and events.",
  나: "Me",
  시스템: "System",
  고정됨: "Pinned",
  답글: "Reply",
  "잡 대기 중 · 앞 잡이 끝나면 시작해요":
    "Job queued · Starts when previous job finishes",
  "입력 중…": "Typing...",
  오류: "Error",
  "작업 로그": "Activity log",
  줄: "Line",
  "빠른 액션": "Quick action",
  일정으로: "To event",
  칸반으로: "To kanban",
  "고정 해제": "Unpin",
  고정: "Pin",
  스레드: "Thread",
  "일정으로 만들기": "Create event",
  날짜: "Date",
  "끝 (선택)": "End (Optional)",
  "명령 고르기": "Choose command",
  "에이전트 부르기": "Call agent",
  "Tab·Enter 선택 · ↑↓ 이동 · Esc 닫기":
    "Tab/Enter to select, Up/Down to navigate, Esc to close",
  "스레드에 답장": "Reply to Thread",
  "메시지 입력": "Message input",
  "스레드에 답장… (/task, /debate 같은 명령도 돼요)":
    "Reply to thread... (Commands like /task, /debate also work)",
  "받는 이 ·": "To ·",
  "@로 에이전트 호출 · /ask는": "Call agent with @ · /ask is",
  " (채널 기본)": " (Channel default)",
  " (기본)": " (Default)",
  보내기: "Send",
  없음: "None",
  "아직 답글이 없어요.": "No replies yet.",
  " · 1분 안에": " · in 1 min",
  "잡 대기 중": "Coding job queued",
  "잡 실행 중": "Coding job running",
  "잡 중단됨": "Coding job stopped",
  "결과 보기": "View results",
  "다시 실행": "Run again",
  로그: "Log",
  "코딩 잡": "Coding job",
  "스레드에서 보기": "View thread",
  "맡길 일": "Task",
  "작업 디렉터리 (비우면 새 폴더)":
    "Work directory (clear to create new folder)",
  "허용:": "Allow:",
  "잡 시작": "Start job",
  "채널·할 일 찾기": "Find channel or task",
  "채널이나 할 일 이름": "Channel or task name",
  "찾는 게 없어요": "No results found",
  "내 공간 일상": "My space daily",
  영역: "Space",
  "홈 · 오늘": "Home · Today",
  홈: "Home",
  "영역 추가": "Add space",
  "설정 닫기": "Close settings",
  설정: "Settings",
  "설정 닫기 (이전 화면으로)": "Close Settings (Go Back)",
  "영역 삭제…": "Delete Space...",
  "영역을 삭제할까요? 채널과 그 안의 내용은 삭제되지 않고 전체에 남아요.":
    "Delete this space? Channels and their contents will remain intact.",
  "영역 삭제": "Delete space",
  이름: "Name",
  "예: 학업": "e.g., Studies",
  과목: "Subjects",
  프로젝트: "Projects",
  전체: "All",
  "지켜보는 중": "Shortcuts",
  알림: "Notifications",
  "승인 대기": "Pending approval",
  리뷰: "Reviews",
  "채널 삭제…": "Delete Channel...",
  "우클릭하여 삭제 메뉴": "Right-click to delete",
  "예: argos": "e.g., argos",
  "예: 자료구조": "e.g., Data Structures",
  "먼저 레일의 + 로 영역을 만들어 주세요.":
    "Create a space first using the Rail + button.",
  "입력 중": "Entering...",
  기본: "Default",
  "실시간 연결됨": "Connected in real-time",
  "연결 중…": "Connecting...",
  "연결 끊김 · 다시 시도 중": "Connection lost · Retrying",
  라이트: "Light",
  다크: "Dark",
  방금: "Just now",
  "사용량 자세히": "View usage details",
  "정보 없음": "No data",
  " · 초기화됨": " · Reset",
  확인: "Checked",
  "코딩 잡: 실행 중": "Coding job: Running",
  "· 오늘": " · Today",
  캘린더: "Calendar",
  볼트: "Vault",
  아직: "Not yet",
  동기화: "Synced",
  대기: "Waiting",
  "사용량 자세히 보기": "View usage details",
  낮음: "Low",
  보통: "Normal",
  높음: "High",
  긴급: "Urgent",
  "카드 상세": "Card details",
  닫기: "Close",
  "이 할 일은 삭제되었거나 찾을 수 없어요.":
    "This task has been deleted or not found.",
  상태: "Status",
  우선순위: "Priority",
  메모: "Note",
  삭제: "Delete",
  만들어짐: "Created",
  "순서 바꿈": "Reorder",
  발자국: "Activity",
  "옆으로 좁히기": "Narrow view",
  "넓게 보기": "Wide view",
  "이 메시지를 찾을 수 없어요.": "Message not found.",
  "에이전트가 지우려는 항목이에요. 승인하기 전에는 아무것도 삭제되지 않아요.":
    "An agent has requested to delete this item. Nothing will be deleted until you approve.",
  "기다리는 승인이 없어요.": "No pending approvals.",
  "고르러 가기": "Review conflicts",
  "일정 추가": "Add event",
  "예: 3주차 퀴즈": "Example: Week 3 quiz",
  반복: "Repeat",
  "반복 일정은 캘린더 앱에서 고쳐 주세요.":
    "Edit repeating events in the Calendar app.",
  저장: "Save",
  피드: "Feed",
  칸반: "Kanban",
  노트: "Notes",
  자료: "Resources",
  수집함: "Inbox",
  "채널 탭": "Channel tabs",
  "] 이전·다음": "Previous/Next",
  "채널을 찾을 수 없어요. 삭제되었을 수 있어요.":
    "No channels found. They may have been deleted.",
  "채널 설정": "Channel settings",
  옵시디언: "Obsidian",
  "내 공간 설정": "Space settings",
  "전체 (영역 없음)": "All (no space)",
  "기본 에이전트 (/ask를 받음)": "Default agent (receives /ask)",
  "앱 기본값 따르기": "Follow app defaults",
  "옵시디언 폴더 (선택)": "Obsidian folder (optional)",
  "옵시디언 폴더 선택": "Select Obsidian folder",
  "볼트 안의 폴더 고르기": "Choose a folder in Vault",
  "앱 설정에서 볼트를 먼저 지정하세요": "Set the Vault first in app settings",
  "이 폴더의 노트·자료가 채널에 보이고, 노트의 체크박스 할 일이 칸반으로 와요.":
    "Notes and files from this folder appear in the channel; checkbox tasks from notes sync to Kanban.",
  "Claude Code 로그인으로 동작": "Operates via Claude Code login",
  "Codex 로그인으로 동작": "Operates via Codex login",
  "Ollama 모델, 이 컴퓨터에서만": "Ollama model, local only",
  읽기: "Read",
  쓰기: "Write",
  "삭제 (허용해도 항상 사용자 승인)":
    "Delete (always requires user approval even if allowed)",
  "커스텀 에이전트": "Custom agent",
  "YAML 가져오기": "Import YAML",
  "봇 만들기": "Create bot",
  "역할과 말투(시스템 프롬프트)와 쓸 수 있는 Argos 도구를 정해 나만의 에이전트를 만들어요. 허용하지 않은 도구는 Argos가 막아요. 메시지에 @이름으로 부르거나 채널의 /ask 담당으로 정할 수 있어요.":
    "Define your custom agent by setting its role, tone (system prompt), and allowed Argos tools. Disallowed tools are blocked by Argos. You can mention the agent in messages using @name or assign it as the /ask handler for a channel.",
  "아직 만든 에이전트가 없어요": "No agents created yet",
  "· 도구": "· Tools",
  개: "items",
  수정: "Edit",
  내보내기: "Export",
  "@이름": "@Name",
  "표시 이름": "Display name",
  "과목 튜터": "Subject tutor",
  아바타: "Avatar",
  "기반 에이전트": "Agent based on",
  "시스템 프롬프트 (역할·말투·규칙)": "System prompt (Role, Tone, Rules)",
  "채널 과목의 볼트 노트를 근거로, 개념을 예시와 함께 짧게 설명하는 튜터다.":
    "A tutor that briefly explains concepts with examples, based on the Vault notes for Channel Subject.",
  "쓸 수 있는 Argos 도구": "Available Argos tools",
  만들기: "Create",
  모델: "Model",
  기본값: "Default",
  "(목록에 없음)": "(None available)",
  "모델 목록을 불러오는 중…": "Loading model list…",
  "비우면 기본값": "Clear to use default",
  "YAML 파일": "YAML file",
  "YAML 내용": "YAML content",
  "name: tutor\ndisplay_name: 과목 튜터\nbackend: llm\ntools: [search_notes]":
    "name: tutor\ndisplay_name: Subject Tutor\nbackend: llm\ntools: [search_notes]",
  가져오기: "Import",
  "드래그로 이동 · 순서는 새로고침 후에도 유지":
    "Drag to move · Order persists after refresh",
  "스페이스로 카드를 들고, 방향키로 옮긴 뒤 스페이스로 내려놓아요. Esc는 취소.":
    "Hold Space to grab a card, use arrow keys to move, release with Space. Press Esc to cancel.",
  "WIP 한도를 넘었어요. 하나 끝내고 시작하는 게 어때요?":
    "You've exceeded your WIP limit. How about finishing one before starting another?",
  "WIP 한도에 닿았어요. 하나 끝내고 시작하는 게 어때요?":
    "You've reached your WIP limit. How about finishing one before starting another?",
  "날짜 없음": "No date",
  "할 일 추가": "Add task",
  "예: 과제2 제출": "e.g., Submit Assignment 2",
  "이 폴더에 자료 파일(PDF, 슬라이드 등)이 없어요.":
    "No resource files (such as PDFs or slides) in this folder.",
  폴더: "Folder",
  관련도: "Relevance",
  경로: "Path",
  "최근 것부터": "Most recent first",
  "오래된 것부터": "Oldest first",
  "잘 맞는 것부터": "Best match first",
  "덜 맞는 것부터": "Least match first",
  가나다순: "Alphabetical (A-Z)",
  역순: "Reverse order",
  "정렬 기준": "Sort by",
  "노트 검색": "Search notes",
  "노트 검색 (제목·본문)": "Search notes (title & body)",
  "찾는 노트가 없어요": "No matching notes found",
  "이 폴더에 노트가 없어요": "No notes in this folder",
  "왼쪽에서 노트를 고르세요": "Select a note from the left",
  "· 읽기 전용": " · Read-only",
  "이 채널에 연결된 옵시디언 폴더가 없어요.":
    "No Obsidian folder connected to this channel.",
  "채널 설정(오른쪽 위 톱니바퀴)에서 폴더를 고르세요. 볼트는 앱 설정에서 지정해요.":
    "Select a folder in Channel settings (top-right gear). Vault is set in App settings.",
  "마감 임박": "Due soon",
  "마감 지남": "Overdue",
  인박스: "Inbox",
  "날짜 없는 할 일": "Dateless task",
  "주간 리뷰": "Weekly review",
  "모두 읽음": "All read",
  "다가오는 마감이나 오래 둔 인박스가 있으면 여기에 알려 드려요.":
    "Shows upcoming due dates or overdue items in your Inbox.",
  "안 읽음": "Unread",
  " · 메신저로 보냄": " · Sent via messenger",
  월: "Mon",
  화: "Tue",
  수: "Wed",
  목: "Thu",
  금: "Fri",
  토: "Sat",
  일: "Sun",
  "마감 D-3·D-1·지남, 오래 둔 인박스(매일":
    "Due in 3 days · Due tomorrow · Overdue, overdue Inbox (daily",
  '시 이후 한 번), 날짜 없는 할 일을 알려 드려요. 사이드바 "알림"에 모이고, 켜 두면 메신저로도 보내요.':
    'once after :00 AM). Also shows dateless tasks. Aggregates in Sidebar "Notifications"; can send via messenger if enabled.',
  "메신저로 보내기 (Hermes)": "Send via messenger (Hermes)",
  "보내지 않음 (앱 안에서만)": "Not sending (app only)",
  "보내는 중…": "Sending…",
  테스트: "Test",
  "브라우저 알림 (창이 뒤에 있을 때)":
    "Browser notifications (when window is minimized)",
  "켜져 있어요.": "Enabled",
  "이 브라우저는 알림을 지원하지 않아요.":
    "This browser does not support notifications.",
  "브라우저 설정에서 막혀 있어요": "Blocked in browser settings",
  "브라우저 알림 켜기": "Enable browser notifications",
  "주간 리뷰 (리뷰 화면에 표시)": "Weekly review (shown on the Review screen)",
  매주: "Every week",
  "리뷰 요일": "Review day of week",
  요일: "Day of week",
  "리뷰 시각": "Review time",
  시: "Hour",
  운영: "Operations",
  "백업과 자동 실행": "Backups and auto-run",
  "데이터베이스 백업 (매일)": "Database backup (daily)",
  "지금 백업": "Backup now",
  "아직 백업이 없어요": "No backups yet",
  "· 최근": "Recent",
  "보관 개수": "Backups to keep",
  "개 보관": " backups kept",
  "로그인할 때 Argos 앱 열기": "Open Argos app when logging in",
  "로그인할 때 Argos 자동 실행": "Auto-run Argos when logging in",
  "macOS 전용": "For macOS only",
  켜짐: "On",
  "등록됨 · 실행 중": "Registered · Running",
  "등록됨 · 다음 로그인부터": "Registered · Starts on next login",
  꺼짐: "Off",
  '로그인하면 Argos 앱이 메뉴 막대에서 조용히 켜져요. 창을 닫아도 서버는 계속 돌아서 아이패드 접속·동기화·알림이 이어져요. 끄려면 메뉴 막대 아이콘의 "Argos 종료". 기록은':
    'When logged in, the Argos app quietly starts from the menu bar. Closing windows keeps the server running for iPad access, sync, and notifications. To stop it, choose "Quit Argos" from the menu bar icon. Your records are',
  ", 기록은": ", records are",
  "지금 시작": "Start now",
  "자동 실행 끄기": "Disable Auto-Start",
  "자동 실행 켜기": "Enable Auto-Start",
  "확인하는 중…": "Checking...",
  "곧 확인해요": "Checking soon",
  "앱 업데이트": "Update app",
  "다시 시작해 업데이트": "Restart to Update",
  "지금 확인": "Check now",
  "Argos 삭제": "Uninstall Argos",
  "Argos 완전 삭제…": "Uninstall Argos…",
  "Argos 완전 삭제": "Uninstall Argos",
  "로그인 시 자동 실행 해제, 키체인의 iCloud 앱 암호 삭제":
    "Disable auto-start at login; remove Keychain's iCloud app password",
  "앱과 캐시를 휴지통으로 옮기고 종료":
    "Move app and cache to Trash, then quit",
  "내 데이터도 휴지통으로 (일정·할 일·메모·대화·백업)":
    "Trash my data too (Events, Tasks, Notes, Conversations, Backups)",
  "끄면 다시 설치했을 때 그대로 이어 쓸 수 있어요.":
    "If turned off, your progress continues when you reinstall.",
  "휴지통을 비우기 전까지는 되돌릴 수 있어요.":
    "You can undo until you empty the Trash.",
  "일부를 옮기지 못했어요:": "Couldn't move some items:",
  "정리하는 중…": "Organizing...",
  "빠른 입력": "Quick entry",
  "생각난 걸 적고 Enter — 인박스로 가요 (/task, /event도 돼요)":
    "Jot down ideas and press Enter — goes to Inbox (/task, /event work too)",
  "인박스에 넣었어요": "Added to Inbox",
  "Enter 보내기 · Shift+Enter 줄바꿈 · Esc 닫기":
    "Send with Enter · Shift+Enter for newline · Escape to close",
  "인박스 열기": "Open inbox",
  "# 주간 리뷰": "# Weekly Review",
  "만드는 중…": "Creating...",
  "이번 주 리뷰 만들기": "Create this week's review",
  "주간 리뷰는 설정한 요일·시간에 이곳에 자동으로 쌓여요. 끝낸 일, 오래된 백로그, 비슷한 수집함 메모를 모아 보여줘요.":
    "Weekly reviews appear here at your chosen time. They bring together completed tasks, aging backlog items, and related Inbox notes.",
  "주간 리뷰 기록": "Weekly review log",
  "불러온 기록에 리뷰가 없어요. 이전 기록을 더 볼 수 있어요.":
    "No reviews in imported logs. You can view more past records.",
  "아직 작성된 리뷰가 없어요.": "No reviews written yet.",
  "주간 리뷰 ·": "Weekly Review ·",
  "이전 기록 더 보기": "View more past records",
  "주간 완료": "Weekly completed",
  "주마다 끝낸 할 일": "Tasks completed this week",
  "처리 시간": "Time spent",
  "만든 뒤 끝내기까지 평균 (최근 30일)":
    "Average time from creation to completion (last 30 days)",
  "아직 끝낸 할 일이 없어요.": "No completed tasks yet.",
  "일 ·": "Task ·",
  "누가 답하고, MCP·스킬, 사용량": "Agents, MCP and skills, usage",
  "입력과 알림": "Input and notifications",
  "정리 모델, 알림, 주간 리뷰":
    "Organizing model, notifications, weekly review",
  연결: "Connections",
  "옵시디언, 애플 캘린더": "Obsidian and Apple Calendar",
  "작업과 운영": "Jobs and maintenance",
  "코딩 잡 폴더, 백업, 자동 실행": "Coding job folder, backup, auto-run",
  "설정 목차": "Settings index",
  "여기서 선택함": "Selected here",
  ".env 설정": ".env settings",
  클라우드: "Cloud",
  로컬: "Local",
  "사용 중": "In use",
  "인박스 분류": "Inbox classification",
  "슬래시 없이 적은 메시지를 할 일·일정으로 정리할 모델을 골라요. 분류하는 동안에도 원문은 인박스에 먼저 저장돼요.":
    "Choose a model to organize slash-free messages into tasks or events. While organizing, the original text is saved to Inbox first.",
  "Hermes를 쓰는 동안에는 .env의 ARGOS_CLASSIFIER_MODEL로 모델을 정해요.":
    "While using Hermes, set the model via ARGOS_CLASSIFIER_MODEL in .env.",
  "Ollama 모델을 불러오는 중…": "Loading Ollama model...",
  "다시 확인": "Check again",
  "입력한 내용이 ollama.com으로 전송돼요": "Your input is sent to ollama.com",
  "이 컴퓨터에서만 실행돼요": "Runs only on this computer",
  "판단 모델 · 빠르게 고르기만 해요": "Decision model · fast, picks only",
  "제목 모델": "Title model",
  "판단 모델은 유형과 채널만 골라요. 할 일·일정의 제목은 여기서 고른 모델이 다듬어요. 고르지 않으면 원문에서 날짜만 뺀 글이 제목이 돼요.":
    "Decision models only pick the type and channel. The model chosen here writes task and event titles. Without one, the title is your text minus its dates.",
  "원문에서 만들기 (모델 없이)": "From the text (no model)",
  "두 모델을 함께 쓰는 방식": "How the two models work together",
  "동시 처리": "At the same time",
  "두 모델이 메모리에 함께 올라갈 때 (예: tev1:0.8b + gemma4:e2b). 분류와 제목을 한꺼번에 받아 가장 빨라요.":
    "When both models fit in memory (e.g. tev1:0.8b + gemma4:e2b). Classification and title arrive together, fastest.",
  "순차 처리": "One after the other",
  "메모리가 부족할 때 (예: tev1:4b + gemma4:e2b). 분류 결과를 먼저 보여 주고, 제목은 하나씩 나중에 다듬어요. 자동 적용은 제목이 나온 뒤에 해요.":
    "When memory is short (e.g. tev1:4b + gemma4:e2b). The suggestion shows first and titles are polished one at a time afterwards. Auto-apply waits for the title.",
  "Ollama에서 찾을 수 없어요": "Not found in Ollama",
  "Ollama에서 찾을 수 없어요 · 다른 모델을 골라 주세요":
    "Not found in Ollama · Please choose another model",
  "분류 끄기": "Turn off categorization",
  "메시지는 인박스에만 쌓이고 직접 정리해요":
    "Messages stay in Inbox until you organize them.",
  "클라우드 모델은 메시지 내용을 ollama.com 서버로 보내요. 개인 일정이 밖으로 나가도 괜찮을 때만 고르세요.":
    "Cloud models send message content to the ollama.com server. Only select this when it's okay for personal events to go outside.",
  "저장했어요. 다음 메시지부터 적용돼요.":
    "Saved. Applies from the next message.",
  "Hermes 게이트웨이 · 자체 도구와 메모리를 가진 에이전트":
    "Hermes Gateway · Agent with its own tools and memory",
  "Claude Code CLI · Argos 도구만 사용 · Claude 사용량을 씀":
    "Claude Code CLI · Uses only Argos tools · Charges for Claude usage",
  "Codex CLI · Argos 도구만 사용 · Codex 사용량을 씀":
    "Codex CLI · Uses only Argos tools · Charges for Codex usage",
  "Ollama 로컬 모델 · 이 컴퓨터에서만 실행 (인박스 분류 모델 사용)":
    "Ollama local model · Runs only on this computer (uses Inbox categorization model)",
  "인박스 분류 모델과 같게": "Same as Inbox categorization model",
  "도구 기본값": "Tool default",
  "에이전트 모델": "Agent model",
  "기본 에이전트가 답할 때 쓰는 모델이에요. 목록은 각 도구가 알려 주는 것이고, 코딩 잡에도 같은 모델을 써요. Hermes 모델은 Hermes 게이트웨이 설정에서 정해요.":
    "The model used when the default Agent replies. The list is provided by each tool, and coding jobs use the same model. The Hermes model is set in the Hermes Gateway settings.",
  "기본 에이전트": "Default agent",
  "/ask를 받을 에이전트예요. 채널 설정에서 채널마다 따로 정할 수도 있어요. 다른 에이전트는 메시지에 @이름으로 불러요.":
    "This is the agent that receives /ask requests. You can set different agents per channel in Channel settings. Other agents are called by @name in messages.",
  "코딩 잡 작업 디렉터리": "Coding job working directory",
  "Claude·Codex 잡은 이 폴더 안에서만 파일을 만들고 고쳐요. 폴더를 정하지 않은 잡은 첫 번째 폴더 아래에 새 폴더를 만들어요.":
    "Claude and Codex jobs create and edit files only in this folder. Jobs without a specified folder create new subfolders under the first folder.",
  "폴더 추가": "Add folder",
  추가: "Add",
  "애플 캘린더 구독": "Apple Calendar subscription",
  'Argos의 일정과 마감(완료하지 않은 할 일)을 캘린더 앱에서 볼 수 있어요. 캘린더 앱에서 "구독 캘린더 추가"에 아래 주소를 넣으면 10분마다 새로 가져와요. 읽기 전용이라 캘린더 앱에서 고친 내용은 Argos에 반영되지 않아요.':
    'View Argos events and deadlines (incomplete tasks) in your Calendar app. Add the address below to "Add Subscribed Calendar" in the Calendar app to refresh every 10 minutes. Read-only: Changes made in the Calendar app won\'t reflect in Argos.',
  복사했어요: "Copied",
  복사: "Copy",
  "주소를 아는 사람은 누구나 일정을 볼 수 있어요. Argos는 이 Mac에서만 열리므로 이 Mac의 캘린더 앱에서 구독하세요. 주소가 새어 나갔다면 새 주소로 바꾸세요.":
    "Anyone with the address can view your events. Since Argos only runs on this Mac, subscribe via the Calendar app on this Mac. If the address is leaked, change it to a new one.",
  "새 주소로 바꿀까요? 지금 주소로 구독한 캘린더는 더 이상 갱신되지 않아요.":
    "Change to a new address? Calendars subscribed with the current address will no longer refresh.",
  "새 주소로 바꾸기": "Change address",
  가져옴: "Imported",
  바뀜: "Changed",
  보냄: "Sent",
  지움: "Deleted",
  충돌: "Conflict",
  "바뀐 것 없음": "No changes",
  "iCloud 캘린더": "iCloud Calendar",
  "· 연결됨": " · Connected",
  "다른 캘린더의 일정은 여기서 보기만 하고 캘린더 앱에서 고쳐요.":
    "View events from other calendars here; edit them in your calendar app.",
  "앱 전용 암호": "App-Specific Password",
  "애플 ID 암호가 아니라": "Not your Apple ID password",
  "애플 계정 관리": "Apple account management",
  "동기화하는 중…": "Syncing...",
  "아직 동기화하지 않았어요": "Not synced yet",
  "지금 동기화": "Sync now",
  "캘린더 → 채널": "Calendar → Channel",
  "읽기 전용": "Read-only",
  "내 공간 (기본)": "My Space (Default)",
  "연결 끊기": "Disconnect",
  건: "item",
  '앱과 "': 'App and ""',
  "Argos 버전 남기기": "Keep Argos version",
  "캘린더 버전 남기기": "Keep Calendar version",
  "가져온 할 일": "Imported tasks",
  "노트에 체크": "Mark in note",
  "앱에 반영": "Reflect in app",
  "바뀐 할 일": "Changed tasks",
  "연결 해제": "Disconnect",
  "옵시디언 볼트": "Obsidian vault",
  "볼트의 노트를 검색하고 읽을 수 있어요. 채널 설정에서 폴더를 연결하면 그 폴더 노트의 체크박스 할 일이 칸반으로 오고, 체크 표시가 양쪽에 반영돼요. 최근 데일리 노트의 할 일은 내 공간으로 와요.":
    "Search and read notes in your Vault. Linking a folder in Channel settings moves checkbox tasks from that folder's notes to the Kanban board, with checkmarks reflected on both sides. Recent Daily Note tasks appear in your Space.",
  "볼트 폴더": "Vault folder",
  "옵시디언에서 찾은 볼트:": "Vaults found in Obsidian:",
  "데일리 노트 폴더": "Daily note folder",
  최근: "Recent",
  "일 데일리 노트의 열린 할 일만 가져와요.":
    "Import only open tasks from the Daily Note.",
  "할 일을 가져오면 노트의 그 줄 끝에":
    "When importing a task, it appends to the end of that note's line,",
  "표시를 붙여 다시 찾아요. 그 표시와 체크 표시 말고는 노트를 바꾸지 않고, 바꾸기 전에 앱 데이터 폴더에 백업을 남겨요. 새 노트는 공부 노트를 저장할 때만 만들어요.":
    "then re-searches using that marker. Only the marker and checkbox are changed; a backup is saved to the app data folder before changes. New notes are created only when saving study notes.",
  "볼트 연결을 끊을까요? 노트 파일은 그대로 남아요.":
    "Disconnect Vault? Note files remain unchanged.",
  "노트를 읽는 중…": "Reading notes…",
  "아직 읽지 않았어요": "Not scanned yet",
  "다시 읽기": "Scan again",
  "에이전트 사용량": "Agent usage",
  "아래 상태줄에 Claude·Codex 요금제의 5시간·주간 사용량을 보여줘요. 몇 분마다 새로 읽고, 90%를 넘은 에이전트를 부르면 스레드에 알려줘요.":
    "Show 5-hour/weekly usage for Claude/Codex plans in the status bar below. Refresh every few minutes and notify threads if an agent exceeds 90%.",
  "Claude Code에 로그인한 계정으로 Claude의 사용량 정보를 읽어요(Claude Code의 /usage와 같은 정보). 처음 한 번 macOS가 키체인 접근을 물어볼 수 있어요. 로그인 정보는 저장하지 않아요.":
    "Read Claude usage info from your logged-in account (e.g., /usage on Claude Code). macOS may request keychain access once. Login credentials are not stored.",
  "로그인한 Codex CLI에게 사용량을 물어봐요.":
    "Ask the logged-in Codex CLI for usage.",
  "읽는 중…": "Reading...",
  "지금 새로 읽기": "Refresh now",
  "오늘 챙길 것": "Today",
  "오늘 일정": "Today's Events",
  "오늘은 일정이 없어요.": "No events today.",
  "가까운 마감이 없어요.": "No upcoming deadlines.",
  "개가 조용히 있어요": " tasks have no due date",
  "날짜 정하기": "Set date",
  "수집함이 비었어요.": "Inbox is empty.",
  넘기기: "Skip",
  "개는 하루 넘게 방치됨": " items have been waiting over a day",
  "전부 보기": "View all",
  "진행 현황": "Progress",
  "채팅·코딩 잡 에이전트. 연결하면 터미널의 Claude Code도 Argos 도구를 써요.":
    "Chat & Coding Job Agent. When connected, terminal's Claude Code also uses Argos tools.",
  "채팅·코딩 잡 에이전트. 연결하면 터미널의 Codex도 Argos 도구를 써요.":
    "Chat & Coding Job Agent. When connected, terminal's Codex also uses Argos tools.",
  "기본 대화 에이전트(메신저 알림 포함). 연결해야 Argos에 일정·할 일을 기록해요.":
    "Basic Chat Agent (includes messenger notifications). Must connect to log events and tasks in Argos.",
  "인박스 분류와 비슷한 메모 묶기를 이 Mac에서 돌리는 로컬 모델.":
    "A local model running note grouping similar to Inbox sorting on this Mac.",
  스킬을: "Skills",
  "설치 안 됨": "Not installed",
  설치됨: "Installed",
  스킬: "Skill",
  "연결하는 중…": "Connecting...",
  "MCP 제거": "Remove MCP",
  "스킬 제거": "Remove skill",
  "모두 제거": "Remove all",
  "에이전트 도구": "Agent tools",
  "), Argos 도구 쓰는 법을 담은": "a guide on how to use Argos tools.",
  "스킬을 설치해요. 누르기 전에는 도구 설정을 바꾸지 않고, 설정에서 언제든 지울 수 있어요.":
    "Install skill. Tool settings won't change until you click it, and you can remove it anytime from Settings.",
  "도구를 찾는 중…": "Searching for tools...",
  "다시 찾는 중…": "Searching again...",
  "다시 찾기": "Search again",
  "처음 설정 다시 보기": "Review setup",
  "로그인할 때 Argos 열기": "Open Argos on login",
  "메뉴 막대에서 조용히 켜져 알림·동기화가 이어져요.":
    "Quietly active in the menu bar, keeping notifications and sync going.",
  켜기: "Turn on",
  환영: "Welcome",
  "기본 설정": "Basic setup",
  마무리: "Finish",
  건너뛰기: "Skip",
  단계: "Step",
  "준비됐어요. 채널에 그냥 적으면 인박스에서 정리되고,":
    "Ready. Notes typed directly into Channels are organized in the Inbox,",
  어디서든: "From anywhere,",
  이전: "Previous",
  다음: "Next",
  "Argos 시작하기": "Start Argos",
  "기다리는 중": "Waiting...",
  매일: "Daily",
  평일: "Weekdays",
  주말: "Weekends",
  "오늘의 루틴": "Today's routines",
  "일 연속": "Day streak",
  "오늘 쉬는 루틴:": "Routines paused today:",
  "루틴 추가": "Add routine",
  "루틴 추가 (매일)": "Add routine (Daily)",
  "루틴 편집": "Edit routine",
  "반복 요일 ·": "Repeat on ·",
  "삭제 메뉴": "Delete menu",
  "레일 표시 (1~2글자, 비우면 이름 첫 글자)":
    "Sidebar icon (1–2 characters; blank uses the first letter)",
  "앱과 캘린더에서 같은 일정을 각각 고쳤어요 (":
    "The same event was changed in Argos and Calendar (",
  "건). 어느 쪽을 남길지 골라 주세요.": "). Choose which version to keep.",
  "/ask를 맡을 채널 (선택)":
    "Channels where this agent handles /ask (optional)",
  보냈어요: "Sent",
  "Hermes가 설치되어 있지 않아 앱 안에서만 알려요.":
    "Hermes isn't installed, so notifications will stay in Argos.",
  "Hermes에 연결된 채널을 불러오는 중…":
    "Loading channels connected to Hermes…",
  "macOS의 launchd에 등록해 로그인하면 서버와 화면(make dev)을 켜고, 꺼지면 다시 켜요. 설정 파일은":
    "Registers with macOS launchd to start the server and app on login and restart them if they stop. The configuration file is at",
  '. 터미널에서 이미 켜 둔 Argos가 있으면 그걸 끈 뒤 "지금 시작"을 누르세요.':
    '. If Argos is already running in Terminal, stop it before clicking "Start now".',
  "자동 실행을 끌까요? 지금 launchd로 실행 중이면 멈춰요.":
    "Turn off automatic startup? Argos will stop if launchd is running it now.",
  "새 버전이 나오면 알아서 받아 설치해 두고, 다음에 다시 시작할 때 적용해요(6시간마다 확인). 데이터는 그대로이고, 업데이트 전에 DB를 백업해요.":
    "Checks for updates every six hours, downloads and installs them, and applies them on the next restart. Your data stays in place; the database is backed up first.",
  "앱만 휴지통에 버리면 에이전트에 등록한 MCP·스킬, 로그인 시 자동 실행, 키체인 암호가 남아요. 여기서 지우면 그것까지 한 번에 정리해요.":
    "Moving only the app to Trash leaves agent MCP and skill registrations, login startup, and Keychain credentials behind. Remove them here as well.",
  "Claude Code·Codex·Hermes에서 Argos MCP와 argos 스킬 제거":
    "Remove Argos MCP and skill from Claude Code, Codex, and Hermes",
  '모든 캘린더의 일정을 Argos로 가져오고, Argos에서 만든 일정은 "':
    'Import events from all calendars into Argos. Events created in Argos go only to the "',
  '" 캘린더에만 써요.': '" calendar.',
  '의 "앱 전용 암호"에서 만든 암호를 넣어 주세요. 암호는 이 Mac의 키체인에만 저장돼요.':
    " and enter the app-specific password you created there. It is stored only in this Mac's Keychain.",
  "Argos가 씀": "Writable by Argos",
  "iCloud 연결을 끊을까요? 키체인의 암호를 지우고, 가져온 일정은 Argos에 남아요.":
    "Disconnect iCloud? The Keychain password will be removed. Imported events will remain in Argos.",
  '" 캘린더에서 둘 다 고쳤어요. 어느 쪽을 남길까요?':
    '" calendar. Which version should be kept?',
  "MCP와 스킬을": "MCP and skill",
  MCP를: "MCP",
  "Argos에 연결": "Connect to Argos",
  "에 Argos가 설치하지 않은 argos 스킬이 있어 건드리지 않아요.":
    " has an argos skill that Argos did not install, so it will be left untouched.",
  '이 Mac에 설치된 도구를 찾았어요. "Argos에 연결"은 각 도구에 Argos의 MCP 주소를 등록하고(':
    'We found the tools installed on this Mac. "Connect to Argos" registers the Argos MCP address with each tool (',
  ", Hermes는": "; for Hermes,",
  "Argos에 오신 걸 환영해요": "Welcome to Argos",
  "Argos는 과목·프로젝트별 채팅 피드에 적은 메모를 할 일·일정으로 정리하고, 에이전트(Claude, Codex, Hermes)와 함께 일하는 이 Mac 전용 대시보드예요.":
    "Argos is a Mac app for organizing notes from course and project channels into tasks and events, with help from Claude, Codex, and Hermes.",
  "몇 가지만 정하면 바로 쓸 수 있어요. 모든 항목은 나중에 설정에서 바꿀 수 있어요. 데이터는 이 Mac의":
    "A few choices will get you started. You can change them later in Settings. Your data stays on this Mac in",
  "에만 저장돼요.": ".",
  "@에이전트": "@agent",
  "로 바로 부를 수도 있어요.": " to call an agent directly.",
  "로 인박스에 빠르게 적을 수 있어요. 창을 닫아도 메뉴 막대에서 계속 돌아요.":
    " to capture a note in Inbox. Argos keeps running in the menu bar after you close the window.",
  "매일 챙길 일을 적어 두면 여기서 체크하고 연속 기록이 쌓여요.":
    "Add a daily routine, check it off here, and build a streak.",
  첨부: "Attachments",
  "첨부 빼기": "Remove attachment",
  "파일 없음": "File missing",
  "첨부는 10개까지 붙일 수 있어요": "You can attach up to 10 files.",
  "파일 붙이기": "Attach files",
  "여기에 놓아 첨부": "Drop to attach",
  "이미 보낸 첨부는 지울 수 없어요":
    "An attachment that was sent cannot be removed.",
  "빈 메시지는 보낼 수 없어요": "Type a message or attach a file.",
  "이미 보낸 첨부예요": "That attachment was already sent.",
  "같은 첨부가 두 번 들어 있어요": "The same attachment is in there twice.",
};
